[server]
headless = true
runOnSave = false

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"
showSidebarNavigation = false

[theme]
base = "light"
primaryColor = "#006A4E"
backgroundColor = "#F5F7FA"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#0B1F33"
